In [1]:
import numpy as np

In [2]:
# Creating the multidimensional array using numpy
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
# Numpy supports subtraction of the above arrays as follows
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
# Calculating the total sales by using numpy dot product.
price_per_unit = np.array([[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
total_sales = np.dot(price_per_unit, units)

total_sales

array([[34400, 50000, 64400]])

#### Exercise

1. Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR



In [8]:
revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [29]:
#converted_revenue = revenue * np.full_like(1,75,shape=(4,3))
# OR
converted_revenue = 75 * revenue

In [30]:
converted_revenue

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])